apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nextjs-express-mysql.fullname" . }}
  labels:
    app: {{ include "nextjs-express-mysql.name" . }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "nextjs-express-mysql.fullname" . }}
                port:
                  number: 80
